apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-data-2
  namespace: stackdome-control-plane
spec:
  selector:
    matchLabels:
      user: ashish
  accessModes:
    - ReadWriteMany
  storageClassName: stackdome-rwmany
  resources:
    requests:
      storage: 5Gi

