---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - workspace.soradev.io
  resources:
  - workspaceresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workspace.soradev.io
  resources:
  - workspaceresources/finalizers
  verbs:
  - update
- apiGroups:
  - workspace.soradev.io
  resources:
  - workspaceresources/status
  verbs:
  - get
  - patch
  - update
- apiGroups: [""]
  resources: ["configmaps", "persistentvolumeclaims", "pods", "services"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
