---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - workspace.soradev.io
  resources:
  - workspacevolumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workspace.soradev.io
  resources:
  - workspacevolumes/finalizers
  verbs:
  - update
- apiGroups:
  - workspace.soradev.io
  resources:
  - workspacevolumes/status
  verbs:
  - get
  - patch
  - update
