# permissions for end users to edit workspaceresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: workspaceresource-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cluster-agent
    app.kubernetes.io/part-of: cluster-agent
    app.kubernetes.io/managed-by: kustomize
  name: workspaceresource-editor-role
rules:
- apiGroups:
  - workspace.soradev.io
  resources:
  - workspaceresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workspace.soradev.io
  resources:
  - workspaceresources/status
  verbs:
  - get
