## Append samples of your project ##
resources:
- workspace_v1alpha1_workspacestate.yaml
- workspace_v1alpha1_workspaceresource.yaml
- workspace_v1alpha1_workspaceapplicationbuild.yaml
- workspace_v1alpha1_workspace.yaml
- workspace_v1alpha1_workspacevolume.yaml
- workspace_v1alpha1_workspaceconfiguration.yaml
- registry_v1alpha1_registry.yaml
- storage_v1alpha1_nfsserver.yaml
- addons_v1alpha1_postgrescluster.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
