apiVersion: registry.stackdome.io/v1alpha1
kind: ClusterRegistry
metadata:
  name: cluster-registry
spec:
  owner:
    type: Organization
    id: engineering-dept
  storage:
    size: 10Gi
  auth:
    htPasswordCredentials:
      credentialsRef:
        secretName: registry-creds
        secretNamespace: stackdome-registry
        usernameKey: username
        passwordKey: password
  retentionPolicy:
    maxRepositoryCount: 100
    tagsPerRepo: 10
    deleteUntagged: true
  port: 5000
---
 kubectl create secret generic registry-creds \
  --from-literal=username='ashish' \
  --from-literal=password='welcome' \
  --namespace stackdome-registry