apiVersion: core.stackdome.io/v1alpha1
kind: StackResource
metadata:
  name: todo-app
spec:
  buildSpec:
    sourceContext:
      git:
        repoUrl: https://github.com/dockersamples/todo-list-app.git
    buildContext: /
    dockerFilePath: Dockerfile
    sourceRevision:
      gitRepo:
        branch:
          name: main
    registry:
      repositoryUrl: cluster-registry.stackdome-registry.svc.cluster.local/ashish/todo-app
      insecure: true
  ports:
  - number: 3000
    exposeToPublic: true
    isHttp: true
    fqdn: "todo.stackdome.io"