apiVersion: workspace.soradev.io/v1alpha1
kind: WorkspaceApplicationBuild
metadata:
  name: front-end
  namespace: ashish-workspace
spec:
  sourceHash: "test-1"
  contextRef:
    workspaceStateName: ashish
    dockerfilePath: Dockerfile
    resourceName: front-end
  registry: local-registry:5000
