apiVersion: workspace.soradev.io/v1alpha1
kind: WorkspaceStorage
metadata:
  namespace: ashish-workspace
  name: ashish
spec:
  resourceStorageSpecs:
  - name: front-end
    type: service
    size: 2Gi
