/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	"fmt"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

type WorkspaceStoragePhase string

const (
	WSReady   WorkspaceStoragePhase = "Ready"
	WSPending WorkspaceStoragePhase = "Pending"
)

type WorkspaceStorageCondition string

const (
	WorkspaceStorageAvailable WorkspaceStorageCondition = "Available"
)

type WorkspaceStorageSpec struct {
	// +kubebuilder:validation:Required
	ResourceStorageSpecs []ResourceStorageSpec `json:"resourceStorageSpecs,omitempty"`
}

type ResourceStorageType string

const (
	SyncingStorageType ResourceStorageType = "SyncingType"
	EmptyStorageType   ResourceStorageType = "EmptyStorageType"
)

type ResourceStorageSpec struct {
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	VolumeName string `json:"volumeName"`
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	Size string              `json:"size"`
	Type ResourceStorageType `json:"type"`
	// +optional
	DontAllowSync      bool `json:"dontAllowSync"`
	NeedsSyncBeforeUse bool `json:"needsSyncBeforeUse"`
	// +optional
	Hash string `json:"hash,omitempty"`
}

type WorkspaceStorageStatus struct {
	// The most recent generation observed by the controller.
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`
	// Conditions is a list of status conditions ths object is in.
	Conditions []metav1.Condition `json:"conditions,omitempty"`
	// DEPRECATED: This field is not part of any API contract
	// it will go away as soon as kubectl can print conditions!
	// Human readable status - please use .Conditions from code
	// +kubebuilder:default=Pending
	Phase WorkspaceStoragePhase `json:"phase,omitempty"`
	// +optional
	WorkspaceVolumeStatus []VolumeStatus `json:"workspaceVolumeInfo,omitempty"`
	// Name of the svc which exposes this storage pod(internally.)
	// +optional
	ServiceName string `json:"serviceName"`
}

type VolumeStatus struct {
	VolumeName string              `json:"volumeName"`
	VolumeType ResourceStorageType `json:"volumeType"`
	// Path within the storage pod where the volume is mounted.
	Subpath   string `json:"subpath"`
	Available bool   `json:"Available"`
	// Applicable to only syncable volume types.
	LastSyncedAt *metav1.Time `json:"lastSyncedAt,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:shortName=ws
// +kubebuilder:printcolumn:name="Phase",type="string",JSONPath=".status.phase"
// This Object is used to describe the storage requirements for services.
// It can be for storing and syncing the code for a service(each service is backed by a WorkspaceResourceStorage) or for
// storing data generated by applications/services. (Like redis, memcached, postgres etc).
type WorkspaceStorage struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   WorkspaceStorageSpec   `json:"spec,omitempty"`
	Status WorkspaceStorageStatus `json:"status,omitempty"`
}

func (w *WorkspaceStorage) HasSyncRequiredStorageResources() bool {
	for _, srs := range w.Spec.ResourceStorageSpecs {
		if srs.NeedsSyncBeforeUse {
			return true
		}
	}
	return false
}

func (w *WorkspaceStorage) MarkAsSynced() {
	for i := range w.Spec.ResourceStorageSpecs {
		curr := &w.Spec.ResourceStorageSpecs[i]
		curr.NeedsSyncBeforeUse = false
	}
}

func (w *WorkspaceStorage) ContainsVolume(volumeName string) bool {
	for i := range w.Spec.ResourceStorageSpecs {
		curr := &w.Spec.ResourceStorageSpecs[i]
		if curr.VolumeName == volumeName {
			return true
		}
	}
	return false
}

func (w *WorkspaceStorage) MountPathForVolume(volumeName string) string {
	return fmt.Sprintf("/%s/%s", w.Name, volumeName)
}

func (w *WorkspaceStorage) VolumeInfo(volumeName string) *VolumeStatus {
	for i := range w.Status.WorkspaceVolumeStatus {
		if w.Status.WorkspaceVolumeStatus[i].VolumeName == volumeName {
			return &w.Status.WorkspaceVolumeStatus[i]
		}
	}
	return nil
}

func (w *WorkspaceStorage) ResourceVolumeSpecFor(volumeName string) *ResourceStorageSpec {
	for i := range w.Spec.ResourceStorageSpecs {
		if w.Spec.ResourceStorageSpecs[i].VolumeName == volumeName {
			return &w.Spec.ResourceStorageSpecs[i]
		}
	}
	return nil
}

//+kubebuilder:object:root=true

// WorkspaceStateList contains a list of WorkspaceState
type WorkspaceStorageList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []WorkspaceStorage `json:"items"`
}

func init() {
	SchemeBuilder.Register(&WorkspaceStorage{}, &WorkspaceStorageList{})
}
