//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupSpec) DeepCopyInto(out *BackupSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupSpec.
func (in *BackupSpec) DeepCopy() *BackupSpec {
	if in == nil {
		return nil
	}
	out := new(BackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapSpec) DeepCopyInto(out *BootstrapSpec) {
	*out = *in
	if in.InitDbSpec != nil {
		in, out := &in.InitDbSpec, &out.InitDbSpec
		*out = new(InitDbSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.RecoverySpec != nil {
		in, out := &in.RecoverySpec, &out.RecoverySpec
		*out = new(RecoverySpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapSpec.
func (in *BootstrapSpec) DeepCopy() *BootstrapSpec {
	if in == nil {
		return nil
	}
	out := new(BootstrapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterBackupSpec) DeepCopyInto(out *ClusterBackupSpec) {
	*out = *in
	if in.ScheduledBaseBackupSpec != nil {
		in, out := &in.ScheduledBaseBackupSpec, &out.ScheduledBaseBackupSpec
		*out = new(ScheduledBaseBackupSpec)
		**out = **in
	}
	if in.LastBaseBackupRequestedAt != nil {
		in, out := &in.LastBaseBackupRequestedAt, &out.LastBaseBackupRequestedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterBackupSpec.
func (in *ClusterBackupSpec) DeepCopy() *ClusterBackupSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterBackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterConnectionInfo) DeepCopyInto(out *ClusterConnectionInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterConnectionInfo.
func (in *ClusterConnectionInfo) DeepCopy() *ClusterConnectionInfo {
	if in == nil {
		return nil
	}
	out := new(ClusterConnectionInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseInfo) DeepCopyInto(out *DatabaseInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseInfo.
func (in *DatabaseInfo) DeepCopy() *DatabaseInfo {
	if in == nil {
		return nil
	}
	out := new(DatabaseInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseSpec) DeepCopyInto(out *DatabaseSpec) {
	*out = *in
	if in.Extensions != nil {
		in, out := &in.Extensions, &out.Extensions
		*out = make([]ExtensionSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseSpec.
func (in *DatabaseSpec) DeepCopy() *DatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(DatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtensionSpec) DeepCopyInto(out *ExtensionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtensionSpec.
func (in *ExtensionSpec) DeepCopy() *ExtensionSpec {
	if in == nil {
		return nil
	}
	out := new(ExtensionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalClusterSpec) DeepCopyInto(out *ExternalClusterSpec) {
	*out = *in
	out.Password = in.Password
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalClusterSpec.
func (in *ExternalClusterSpec) DeepCopy() *ExternalClusterSpec {
	if in == nil {
		return nil
	}
	out := new(ExternalClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FencingSpec) DeepCopyInto(out *FencingSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FencingSpec.
func (in *FencingSpec) DeepCopy() *FencingSpec {
	if in == nil {
		return nil
	}
	out := new(FencingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageCatalogRef) DeepCopyInto(out *ImageCatalogRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageCatalogRef.
func (in *ImageCatalogRef) DeepCopy() *ImageCatalogRef {
	if in == nil {
		return nil
	}
	out := new(ImageCatalogRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImportSpec) DeepCopyInto(out *ImportSpec) {
	*out = *in
	if in.Databases != nil {
		in, out := &in.Databases, &out.Databases
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SourceClusterSpec != nil {
		in, out := &in.SourceClusterSpec, &out.SourceClusterSpec
		*out = new(ExternalClusterSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImportSpec.
func (in *ImportSpec) DeepCopy() *ImportSpec {
	if in == nil {
		return nil
	}
	out := new(ImportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitDbSpec) DeepCopyInto(out *InitDbSpec) {
	*out = *in
	if in.Import != nil {
		in, out := &in.Import, &out.Import
		*out = new(ImportSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitDbSpec.
func (in *InitDbSpec) DeepCopy() *InitDbSpec {
	if in == nil {
		return nil
	}
	out := new(InitDbSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstancePlacementSpec) DeepCopyInto(out *InstancePlacementSpec) {
	*out = *in
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstancePlacementSpec.
func (in *InstancePlacementSpec) DeepCopy() *InstancePlacementSpec {
	if in == nil {
		return nil
	}
	out := new(InstancePlacementSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLSpec) DeepCopyInto(out *PostgreSQLSpec) {
	*out = *in
	if in.ImageCatalogRef != nil {
		in, out := &in.ImageCatalogRef, &out.ImageCatalogRef
		*out = new(ImageCatalogRef)
		**out = **in
	}
	if in.PostgresConf != nil {
		in, out := &in.PostgresConf, &out.PostgresConf
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLSpec.
func (in *PostgreSQLSpec) DeepCopy() *PostgreSQLSpec {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresCluster) DeepCopyInto(out *PostgresCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresCluster.
func (in *PostgresCluster) DeepCopy() *PostgresCluster {
	if in == nil {
		return nil
	}
	out := new(PostgresCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PostgresCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresClusterList) DeepCopyInto(out *PostgresClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PostgresCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresClusterList.
func (in *PostgresClusterList) DeepCopy() *PostgresClusterList {
	if in == nil {
		return nil
	}
	out := new(PostgresClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PostgresClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresClusterOutputs) DeepCopyInto(out *PostgresClusterOutputs) {
	*out = *in
	if in.ClusterConnection != nil {
		in, out := &in.ClusterConnection, &out.ClusterConnection
		*out = new(ClusterConnectionInfo)
		**out = **in
	}
	if in.Databases != nil {
		in, out := &in.Databases, &out.Databases
		*out = make([]DatabaseInfo, len(*in))
		copy(*out, *in)
	}
	if in.SuperUserCredentialSecret != nil {
		in, out := &in.SuperUserCredentialSecret, &out.SuperUserCredentialSecret
		*out = new(string)
		**out = **in
	}
	if in.UserCredentialSecrets != nil {
		in, out := &in.UserCredentialSecrets, &out.UserCredentialSecrets
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresClusterOutputs.
func (in *PostgresClusterOutputs) DeepCopy() *PostgresClusterOutputs {
	if in == nil {
		return nil
	}
	out := new(PostgresClusterOutputs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresClusterSpec) DeepCopyInto(out *PostgresClusterSpec) {
	*out = *in
	in.ReplicasSpec.DeepCopyInto(&out.ReplicasSpec)
	if in.PostgreSQLSpec != nil {
		in, out := &in.PostgreSQLSpec, &out.PostgreSQLSpec
		*out = new(PostgreSQLSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.BootstrapSpec != nil {
		in, out := &in.BootstrapSpec, &out.BootstrapSpec
		*out = new(BootstrapSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.StorageSpec != nil {
		in, out := &in.StorageSpec, &out.StorageSpec
		*out = new(StorageSpec)
		**out = **in
	}
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	if in.InstancePlacementSpec != nil {
		in, out := &in.InstancePlacementSpec, &out.InstancePlacementSpec
		*out = new(InstancePlacementSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ClusterBackupSpec != nil {
		in, out := &in.ClusterBackupSpec, &out.ClusterBackupSpec
		*out = new(ClusterBackupSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.FencingSpec != nil {
		in, out := &in.FencingSpec, &out.FencingSpec
		*out = new(FencingSpec)
		**out = **in
	}
	if in.Databases != nil {
		in, out := &in.Databases, &out.Databases
		*out = make([]DatabaseSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresClusterSpec.
func (in *PostgresClusterSpec) DeepCopy() *PostgresClusterSpec {
	if in == nil {
		return nil
	}
	out := new(PostgresClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresClusterStatus) DeepCopyInto(out *PostgresClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Outputs != nil {
		in, out := &in.Outputs, &out.Outputs
		*out = new(PostgresClusterOutputs)
		(*in).DeepCopyInto(*out)
	}
	if in.LastImmeadiateBackupProcessedAt != nil {
		in, out := &in.LastImmeadiateBackupProcessedAt, &out.LastImmeadiateBackupProcessedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresClusterStatus.
func (in *PostgresClusterStatus) DeepCopy() *PostgresClusterStatus {
	if in == nil {
		return nil
	}
	out := new(PostgresClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoveryFromObjectStoreSpec) DeepCopyInto(out *RecoveryFromObjectStoreSpec) {
	*out = *in
	if in.RecoveryTarget != nil {
		in, out := &in.RecoveryTarget, &out.RecoveryTarget
		*out = new(RecoveryTargetSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoveryFromObjectStoreSpec.
func (in *RecoveryFromObjectStoreSpec) DeepCopy() *RecoveryFromObjectStoreSpec {
	if in == nil {
		return nil
	}
	out := new(RecoveryFromObjectStoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoverySpec) DeepCopyInto(out *RecoverySpec) {
	*out = *in
	if in.ObjectStoreSpec != nil {
		in, out := &in.ObjectStoreSpec, &out.ObjectStoreSpec
		*out = new(RecoveryFromObjectStoreSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.BackupSpec != nil {
		in, out := &in.BackupSpec, &out.BackupSpec
		*out = new(BackupSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoverySpec.
func (in *RecoverySpec) DeepCopy() *RecoverySpec {
	if in == nil {
		return nil
	}
	out := new(RecoverySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoveryTargetSpec) DeepCopyInto(out *RecoveryTargetSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoveryTargetSpec.
func (in *RecoveryTargetSpec) DeepCopy() *RecoveryTargetSpec {
	if in == nil {
		return nil
	}
	out := new(RecoveryTargetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicasSpec) DeepCopyInto(out *ReplicasSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicasSpec.
func (in *ReplicasSpec) DeepCopy() *ReplicasSpec {
	if in == nil {
		return nil
	}
	out := new(ReplicasSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduledBaseBackupSpec) DeepCopyInto(out *ScheduledBaseBackupSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduledBaseBackupSpec.
func (in *ScheduledBaseBackupSpec) DeepCopy() *ScheduledBaseBackupSpec {
	if in == nil {
		return nil
	}
	out := new(ScheduledBaseBackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageSpec.
func (in *StorageSpec) DeepCopy() *StorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSpec)
	in.DeepCopyInto(out)
	return out
}
