// Code generated by MockGen. DO NOT EDIT.
// Source: internal/controller/stackresource/workload_reconciler.go
//
// Generated by this command:
//
//	mockgen -package=mocks -source=internal/controller/stackresource/workload_reconciler.go -destination=internal/controller/mocks/mock_dependency_checker.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	v1alpha1 "stackdome.io/cluster-agent/api/core/v1alpha1"
)

// MockDependencyChecker is a mock of DependencyChecker interface.
type MockDependencyChecker struct {
	ctrl     *gomock.Controller
	recorder *MockDependencyCheckerMockRecorder
	isgomock struct{}
}

// MockDependencyCheckerMockRecorder is the mock recorder for MockDependencyChecker.
type MockDependencyCheckerMockRecorder struct {
	mock *MockDependencyChecker
}

// NewMockDependencyChecker creates a new mock instance.
func NewMockDependencyChecker(ctrl *gomock.Controller) *MockDependencyChecker {
	mock := &MockDependencyChecker{ctrl: ctrl}
	mock.recorder = &MockDependencyCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDependencyChecker) EXPECT() *MockDependencyCheckerMockRecorder {
	return m.recorder
}

// DependenciesAvailable mocks base method.
func (m *MockDependencyChecker) DependenciesAvailable(ctx context.Context, resource *v1alpha1.StackResource) (bool, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DependenciesAvailable", ctx, resource)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DependenciesAvailable indicates an expected call of DependenciesAvailable.
func (mr *MockDependencyCheckerMockRecorder) DependenciesAvailable(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DependenciesAvailable", reflect.TypeOf((*MockDependencyChecker)(nil).DependenciesAvailable), ctx, resource)
}

// VolumeMountsReadyForUse mocks base method.
func (m *MockDependencyChecker) VolumeMountsReadyForUse(ctx context.Context, resource *v1alpha1.StackResource) (bool, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VolumeMountsReadyForUse", ctx, resource)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// VolumeMountsReadyForUse indicates an expected call of VolumeMountsReadyForUse.
func (mr *MockDependencyCheckerMockRecorder) VolumeMountsReadyForUse(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VolumeMountsReadyForUse", reflect.TypeOf((*MockDependencyChecker)(nil).VolumeMountsReadyForUse), ctx, resource)
}
