// Code generated by MockGen. DO NOT EDIT.
// Source: internal/controller/stackresource/workload/reconciler.go
//
// Generated by this command:
//
//	mockgen -package=mocks -source=internal/controller/stackresource/workload/reconciler.go -destination=internal/controller/mocks/mock_dependency_checker.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	v1alpha1 "stackdome.io/cluster-agent/api/core/v1alpha1"
)

// MockDependencyChecker is a mock of DependencyChecker interface.
type MockDependencyChecker struct {
	ctrl     *gomock.Controller
	recorder *MockDependencyCheckerMockRecorder
	isgomock struct{}
}

// MockDependencyCheckerMockRecorder is the mock recorder for MockDependencyChecker.
type MockDependencyCheckerMockRecorder struct {
	mock *MockDependencyChecker
}

// NewMockDependencyChecker creates a new mock instance.
func NewMockDependencyChecker(ctrl *gomock.Controller) *MockDependencyChecker {
	mock := &MockDependencyChecker{ctrl: ctrl}
	mock.recorder = &MockDependencyCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDependencyChecker) EXPECT() *MockDependencyCheckerMockRecorder {
	return m.recorder
}

// DependenciesAvailable mocks base method.
func (m *MockDependencyChecker) DependenciesAvailable(ctx context.Context, resource *v1alpha1.StackResource) (bool, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DependenciesAvailable", ctx, resource)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DependenciesAvailable indicates an expected call of DependenciesAvailable.
func (mr *MockDependencyCheckerMockRecorder) DependenciesAvailable(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DependenciesAvailable", reflect.TypeOf((*MockDependencyChecker)(nil).DependenciesAvailable), ctx, resource)
}

// VolumeMountsReadyForUse mocks base method.
func (m *MockDependencyChecker) VolumeMountsReadyForUse(ctx context.Context, resource *v1alpha1.StackResource) (bool, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VolumeMountsReadyForUse", ctx, resource)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// VolumeMountsReadyForUse indicates an expected call of VolumeMountsReadyForUse.
func (mr *MockDependencyCheckerMockRecorder) VolumeMountsReadyForUse(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VolumeMountsReadyForUse", reflect.TypeOf((*MockDependencyChecker)(nil).VolumeMountsReadyForUse), ctx, resource)
}

// MockStatusReporter is a mock of StatusReporter interface.
type MockStatusReporter struct {
	ctrl     *gomock.Controller
	recorder *MockStatusReporterMockRecorder
	isgomock struct{}
}

// MockStatusReporterMockRecorder is the mock recorder for MockStatusReporter.
type MockStatusReporterMockRecorder struct {
	mock *MockStatusReporter
}

// NewMockStatusReporter creates a new mock instance.
func NewMockStatusReporter(ctrl *gomock.Controller) *MockStatusReporter {
	mock := &MockStatusReporter{ctrl: ctrl}
	mock.recorder = &MockStatusReporterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatusReporter) EXPECT() *MockStatusReporterMockRecorder {
	return m.recorder
}

// ReportFailed mocks base method.
func (m *MockStatusReporter) ReportFailed(r *v1alpha1.StackResource, reason, msg string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ReportFailed", r, reason, msg)
}

// ReportFailed indicates an expected call of ReportFailed.
func (mr *MockStatusReporterMockRecorder) ReportFailed(r, reason, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportFailed", reflect.TypeOf((*MockStatusReporter)(nil).ReportFailed), r, reason, msg)
}

// ReportNotReady mocks base method.
func (m *MockStatusReporter) ReportNotReady(r *v1alpha1.StackResource, reason, msg string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ReportNotReady", r, reason, msg)
}

// ReportNotReady indicates an expected call of ReportNotReady.
func (mr *MockStatusReporterMockRecorder) ReportNotReady(r, reason, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportNotReady", reflect.TypeOf((*MockStatusReporter)(nil).ReportNotReady), r, reason, msg)
}

// ReportReady mocks base method.
func (m *MockStatusReporter) ReportReady(r *v1alpha1.StackResource) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ReportReady", r)
}

// ReportReady indicates an expected call of ReportReady.
func (mr *MockStatusReporterMockRecorder) ReportReady(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportReady", reflect.TypeOf((*MockStatusReporter)(nil).ReportReady), r)
}

// SetCondition mocks base method.
func (m *MockStatusReporter) SetCondition(r *v1alpha1.StackResource, condType v1alpha1.StackResourceStatusCondition, ready bool, reason, msg string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetCondition", r, condType, ready, reason, msg)
}

// SetCondition indicates an expected call of SetCondition.
func (mr *MockStatusReporterMockRecorder) SetCondition(r, condType, ready, reason, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCondition", reflect.TypeOf((*MockStatusReporter)(nil).SetCondition), r, condType, ready, reason, msg)
}
